# Generated by Django 5.0.6 on 2024-05-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtisanServices',
            new_name='Services',
        ),
    ]
