# Generated by Django 5.0.6 on 2024-05-09 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_artisanservices_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_orders_for_this_service', to='api.services'),
        ),
    ]
