# Generated by Django 5.0.6 on 2024-05-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orders_created_at_orders_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
